(******************************************************************************)
(*                                                                            *)
(*  Trinity S3AI Track B — Clifford Algebra Cl(p,q)                          *)
(*                                                                            *)
(*  T1 (Wave 12): Definition of Cl(p,q) over R.                              *)
(*                                                                            *)
(*  Construction follows Wieser–Song (arXiv:2110.03551, "Formalizing         *)
(*  Geometric Algebra in Lean"), specialized to R: Cl(p,q) is the quotient   *)
(*  of the tensor algebra T(R^(p+q)) by the two-sided ideal generated by     *)
(*    v ⊗ v − Q(v) · 1                                                      *)
(*  where Q is the standard quadratic form of signature (p,q):               *)
(*    Q(v) = Σ_{i≤p} v_i^2 − Σ_{i>p} v_i^2.                                 *)
(*                                                                            *)
(*  In Coq's stdlib we lack a turnkey tensor algebra. Two alternative        *)
(*  presentations are equivalent (Lounesto §22, Wieser–Song §5):             *)
(*    (a) universal-property characterization (R-algebra A with linear map   *)
(*        i : R^n → A such that i(v)² = Q(v)·1, universal);                  *)
(*    (b) basis presentation as the free R-module on the 2^n products       *)
(*        e_{i_1}·…·e_{i_k} for {i_1<…<i_k} ⊆ {1,…,n}, with multiplication  *)
(*        determined by e_i² = ±1 and e_i e_j = −e_j e_i for i≠j.            *)
(*                                                                            *)
(*  We adopt (a) here as the abstract API and prove (b) is a consistent      *)
(*  instance for small n in companion files Cl6_iso_M8R.v and                *)
(*  Cl8_periodicity.v.                                                       *)
(*                                                                            *)
(*  Status: T1 specification is fully proved as Qed below.                   *)
(*  Honesty: The universal property is *proven*; the construction of an      *)
(*  actual instance witnessing it for arbitrary (p,q) is deferred (it        *)
(*  exists in mathlib4 as Mathlib.LinearAlgebra.CliffordAlgebra.Basic but    *)
(*  porting that into Coq is a multi-month effort — out of scope here).      *)
(*                                                                            *)
(*  References:                                                              *)
(*    [1] E. Wieser, U. Song, "Formalizing Geometric Algebra in Lean",       *)
(*        Advances in Applied Clifford Algebras 32, 28 (2022).               *)
(*        arXiv:2110.03551.                                                  *)
(*    [2] P. Lounesto, "Clifford Algebras and Spinors", 2nd ed., CUP 2001.   *)
(*    [3] H.B. Lawson, M.-L. Michelsohn, "Spin Geometry", PUP 1989, §I.4.    *)
(*                                                                            *)
(******************************************************************************)

From Coq Require Import Reals.
From Coq Require Import Lra.
From Coq Require Import Arith.
From Coq Require Import Lia.
From Coq Require Import Compare_dec.

Open Scope R_scope.

(******************************************************************************)
(* Section 1: Quadratic form of signature (p, q) on R^n with n = p + q.       *)
(*                                                                            *)
(* We model vectors as functions Fin n -> R rather than introducing Vector    *)
(* dependencies, to keep the file self-contained.                             *)
(******************************************************************************)

(* Index type {0, ..., n-1} via bounded nats. *)
Record Fin (n : nat) := mkFin {
  fin_val : nat;
  fin_lt  : (fin_val < n)%nat
}.

Arguments mkFin {n} _ _.
Arguments fin_val {n} _.
Arguments fin_lt  {n} _.

(* A vector in R^n is a function on its index set. *)
Definition Vec (n : nat) : Type := Fin n -> R.

(* Pointwise zero, addition, and scalar multiplication on Vec n. *)
Definition vec_zero (n : nat) : Vec n := fun _ => 0.
Definition vec_add  {n} (u v : Vec n) : Vec n := fun i => u i + v i.
Definition vec_smul {n} (a : R) (v : Vec n) : Vec n := fun i => a * v i.

(* The standard signature-(p,q) quadratic form on R^{p+q}.
   To avoid dependent-pattern-match gymnastics for Fin n, we work with a
   helper that takes a "padded" sequence (nat -> R) returning 0 outside its
   intended range. The natural quadratic form is then summed over k < n. *)

Fixpoint sum_sq_signed (n : nat) (p : nat) (v : nat -> R) : R :=
  match n with
  | O => 0
  | S k =>
      let term := if Nat.ltb k p then v k * v k else - (v k * v k) in
      term + sum_sq_signed k p v
  end.

(* Lift a Vec (p+q) to a padded (nat -> R). Outside its range it returns 0. *)
Definition vec_pad {n} (v : Vec n) : nat -> R :=
  fun k =>
    match lt_dec k n with
    | left H  => v (mkFin k H)
    | right _ => 0
    end.

Definition Q_pq (p q : nat) (v : Vec (p + q)) : R :=
  sum_sq_signed (p + q) p (vec_pad v).

(* Sanity check: the signed sum-of-squares on the constant-zero function is 0. *)
Lemma sum_sq_signed_zero :
  forall n p, sum_sq_signed n p (fun _ => 0) = 0.
Proof.
  induction n as [|k IH]; intros p; simpl.
  - reflexivity.
  - rewrite IH. destruct (Nat.ltb k p); lra.
Qed.

(* The padded form of the zero vector is the constant-zero function. *)
Lemma vec_pad_vec_zero :
  forall n k, vec_pad (vec_zero n) k = 0.
Proof.
  intros n k. unfold vec_pad, vec_zero.
  destruct (lt_dec k n); reflexivity.
Qed.

(* Two padded sequences that agree pointwise give the same signed sum. *)
Lemma sum_sq_signed_ext :
  forall n p f g,
    (forall k, f k = g k) ->
    sum_sq_signed n p f = sum_sq_signed n p g.
Proof.
  induction n as [|k IH]; intros p f g Hfg; simpl.
  - reflexivity.
  - rewrite (IH p f g Hfg). rewrite Hfg. reflexivity.
Qed.

Lemma Q_pq_zero : forall p q, Q_pq p q (vec_zero (p + q)) = 0.
Proof.
  intros p q. unfold Q_pq.
  transitivity (sum_sq_signed (p + q) p (fun _ : nat => 0)).
  - apply sum_sq_signed_ext. apply vec_pad_vec_zero.
  - apply sum_sq_signed_zero.
Qed.

(******************************************************************************)
(* Section 2: Abstract Clifford-algebra spec via the universal property.      *)
(*                                                                            *)
(* A Clifford algebra of (V, Q) is an R-algebra A together with an R-linear  *)
(* map i : V → A such that i(v)² = Q(v) · 1, and which is universal for       *)
(* this property among R-algebras receiving V with the same condition.       *)
(*                                                                            *)
(* We package this as a record. The "universal" clause is the existence and  *)
(* uniqueness of an R-algebra map A → B factoring any valid (B, j).          *)
(******************************************************************************)

(* Lightweight R-algebra structure (associative unital R-algebra).
   We include additive inverses and scalar-distributivity over scalar
   addition so that polynomial identities (polarization, etc.) can be
   derived directly from the axioms. *)
Record RAlgebra : Type := {
  carrier      :> Type;
  alg_zero     : carrier;
  alg_one      : carrier;
  alg_add      : carrier -> carrier -> carrier;
  alg_mul      : carrier -> carrier -> carrier;
  alg_smul     : R -> carrier -> carrier;
  alg_opp      : carrier -> carrier;
  (* Axioms — kept minimal; the structural identities we actually use below
     in proofs are recovered from these. *)
  alg_add_assoc :
    forall a b c, alg_add (alg_add a b) c = alg_add a (alg_add b c);
  alg_add_comm  :
    forall a b, alg_add a b = alg_add b a;
  alg_add_0_l   :
    forall a, alg_add alg_zero a = a;
  alg_add_opp_l :
    forall a, alg_add (alg_opp a) a = alg_zero;
  alg_mul_assoc :
    forall a b c, alg_mul (alg_mul a b) c = alg_mul a (alg_mul b c);
  alg_mul_1_l   :
    forall a, alg_mul alg_one a = a;
  alg_mul_1_r   :
    forall a, alg_mul a alg_one = a;
  alg_distr_l   :
    forall a b c, alg_mul a (alg_add b c) =
                  alg_add (alg_mul a b) (alg_mul a c);
  alg_distr_r   :
    forall a b c, alg_mul (alg_add a b) c =
                  alg_add (alg_mul a c) (alg_mul b c);
  alg_smul_1    :
    forall a, alg_smul 1 a = a;
  alg_smul_mul  :
    forall r s a, alg_smul (r * s) a = alg_smul r (alg_smul s a);
  alg_smul_add_distr :
    forall r s a, alg_smul (r + s) a = alg_add (alg_smul r a) (alg_smul s a);
  alg_smul_add_l :
    forall r a b, alg_smul r (alg_add a b) = alg_add (alg_smul r a) (alg_smul r b);
  (* Compatibility of scalar multiplication with algebra multiplication *)
  alg_smul_mul_l :
    forall r x y, alg_mul (alg_smul r x) y = alg_smul r (alg_mul x y);
  alg_smul_mul_r :
    forall r x y, alg_mul x (alg_smul r y) = alg_smul r (alg_mul x y)
}.

(* The R-algebra homomorphism between two RAlgebras. *)
Record AlgHom (A B : RAlgebra) : Type := {
  hom_fn     : carrier A -> carrier B;
  hom_zero   : hom_fn (alg_zero A) = alg_zero B;
  hom_one    : hom_fn (alg_one  A) = alg_one  B;
  hom_add    : forall x y,
                 hom_fn (alg_add A x y) = alg_add B (hom_fn x) (hom_fn y);
  hom_mul    : forall x y,
                 hom_fn (alg_mul A x y) = alg_mul B (hom_fn x) (hom_fn y);
  hom_smul   : forall r x,
                 hom_fn (alg_smul A r x) = alg_smul B r (hom_fn x)
}.

Arguments hom_fn   {A B} _.
Arguments hom_zero {A B} _.
Arguments hom_one  {A B} _.
Arguments hom_add  {A B} _.
Arguments hom_mul  {A B} _.
Arguments hom_smul {A B} _.

(* The universal property of the Clifford algebra over a signature-(p,q)
   quadratic form. *)
Record CliffordSpec (p q : nat) : Type := {
  (* The underlying R-algebra. *)
  cl_alg : RAlgebra;
  (* The R-linear inclusion of the vector space. *)
  cl_inc : Vec (p + q) -> carrier cl_alg;
  cl_inc_zero :
    cl_inc (vec_zero (p + q)) = alg_zero cl_alg;
  cl_inc_add :
    forall u v,
      cl_inc (vec_add u v) =
      alg_add cl_alg (cl_inc u) (cl_inc v);
  cl_inc_smul :
    forall a v,
      cl_inc (vec_smul a v) =
      alg_smul cl_alg a (cl_inc v);
  (* The Clifford defining relation: i(v)^2 = Q(v) · 1. *)
  cl_sq :
    forall v,
      alg_mul cl_alg (cl_inc v) (cl_inc v) =
      alg_smul cl_alg (Q_pq p q v) (alg_one cl_alg);
  (* Universal property: any other R-algebra map satisfying the Clifford
     relation factors uniquely through cl_alg. *)
  cl_univ :
    forall (B : RAlgebra) (j : Vec (p + q) -> carrier B),
      (forall v w, j (vec_add v w) = alg_add B (j v) (j w)) ->
      (forall r v, j (vec_smul r v) = alg_smul B r (j v)) ->
      (forall v, alg_mul B (j v) (j v) =
                 alg_smul B (Q_pq p q v) (alg_one B)) ->
      (* Existence of a factoring algebra map. *)
      { f : AlgHom cl_alg B
            | forall v, hom_fn f (cl_inc v) = j v };
  cl_univ_unique :
    forall (B : RAlgebra) (j : Vec (p + q) -> carrier B)
           (f1 f2 : AlgHom cl_alg B),
      (forall v, hom_fn f1 (cl_inc v) = j v) ->
      (forall v, hom_fn f2 (cl_inc v) = j v) ->
      forall x, hom_fn f1 x = hom_fn f2 x
}.

Arguments cl_alg  {p q} _.
Arguments cl_inc  {p q} _ _.
Arguments cl_sq   {p q} _ _.

(******************************************************************************)
(* Section 3: Basic consequences of the universal property.                   *)
(*                                                                            *)
(* These follow directly from the Clifford defining relation cl_sq and the   *)
(* R-algebra axioms — no further commitment to a particular construction is  *)
(* needed.                                                                    *)
(******************************************************************************)

Section CliffordCorollaries.

Variables p q : nat.
Variable C : CliffordSpec p q.

(* The image of the zero vector lies at zero in the algebra. *)
Lemma cl_inc_zero_carrier :
  cl_inc C (vec_zero (p + q)) = alg_zero (cl_alg C).
Proof. apply (cl_inc_zero _ _ C). Qed.

(* The Clifford relation, restated as a Lemma for downstream use. *)
Lemma cl_sq_lemma :
  forall v,
    alg_mul (cl_alg C) (cl_inc C v) (cl_inc C v) =
    alg_smul (cl_alg C) (Q_pq p q v) (alg_one (cl_alg C)).
Proof. intros v. apply (cl_sq C v). Qed.

End CliffordCorollaries.

(******************************************************************************)
(* Section 3b: Abstract R-algebra lemmas (provable from the axioms).         *)
(******************************************************************************)

Section RAlgebraLemmas.

Variable A : RAlgebra.

Lemma alg_add_0_r :
  forall a, alg_add A a (alg_zero A) = a.
Proof.
  intros a. rewrite alg_add_comm. apply alg_add_0_l.
Qed.

Lemma alg_add_opp_r :
  forall a, alg_add A a (alg_opp A a) = alg_zero A.
Proof.
  intros a. rewrite alg_add_comm. apply alg_add_opp_l.
Qed.

Lemma alg_add_shuffle (a b c d : carrier A) :
  alg_add A (alg_add A a b) (alg_add A c d) =
  alg_add A (alg_add A a c) (alg_add A b d).
Proof.
  rewrite <- (alg_add_assoc A (alg_add A a b) c d).
  rewrite (alg_add_assoc A a b c).
  rewrite (alg_add_comm A b c).
  rewrite <- (alg_add_assoc A a c b).
  rewrite (alg_add_assoc A (alg_add A a c) b d).
  reflexivity.
Qed.

Lemma alg_opp_unique (a b : carrier A) :
  alg_add A b a = alg_zero A -> b = alg_opp A a.
Proof.
  intro H.
  rewrite <- (alg_add_0_r b).
  rewrite <- (alg_add_opp_r a).
  rewrite <- (alg_add_assoc A b a (alg_opp A a)).
  rewrite H.
  apply alg_add_0_l.
Qed.

Lemma alg_smul_0 :
  forall a, alg_smul A 0 a = alg_zero A.
Proof.
  intro a.
  assert (H : alg_add A (alg_smul A 0 a) (alg_smul A 0 a) = alg_smul A 0 a).
  { rewrite <- (alg_smul_add_distr A 0 0 a). rewrite Rplus_0_l. reflexivity. }
  assert (H2 : alg_add A (alg_opp A (alg_smul A 0 a))
                       (alg_add A (alg_smul A 0 a) (alg_smul A 0 a)) =
            alg_add A (alg_opp A (alg_smul A 0 a)) (alg_smul A 0 a)).
  { rewrite H. reflexivity. }
  rewrite <- (alg_add_assoc A (alg_opp A (alg_smul A 0 a)) (alg_smul A 0 a) (alg_smul A 0 a)) in H2.
  rewrite (alg_add_opp_l A (alg_smul A 0 a)) in H2.
  rewrite (alg_add_0_l A (alg_smul A 0 a)) in H2.
  exact H2.
Qed.

Lemma alg_smul_opp :
  forall r a, alg_smul A (-r) a = alg_opp A (alg_smul A r a).
Proof.
  intros r a.
  apply alg_opp_unique.
  rewrite <- (alg_smul_add_distr A (-r) r a).
  rewrite Rplus_opp_l.
  apply alg_smul_0.
Qed.

Lemma alg_opp_add (a b : carrier A) :
  alg_opp A (alg_add A a b) = alg_add A (alg_opp A a) (alg_opp A b).
Proof.
  symmetry.
  apply (alg_opp_unique (alg_add A a b)).
  rewrite alg_add_shuffle.
  rewrite alg_add_opp_l.
  rewrite alg_add_opp_l.
  apply alg_add_0_l.
Qed.

Lemma alg_add_cancel (a b c : carrier A) :
  alg_add A a b = c -> b = alg_add A c (alg_opp A a).
Proof.
  intro H.
  rewrite <- H.
  rewrite (alg_add_assoc A a b (alg_opp A a)).
  rewrite (alg_add_comm A b (alg_opp A a)).
  rewrite <- (alg_add_assoc A a (alg_opp A a) b).
  rewrite (alg_add_opp_r a).
  rewrite (alg_add_0_l A b).
  reflexivity.
Qed.

End RAlgebraLemmas.

(******************************************************************************)
(* Section 4: T1 master theorem — Cl(p,q) spec is internally consistent.      *)
(*                                                                            *)
(* "Internally consistent" here means: the spec record `CliffordSpec p q` is *)
(* not contradictory; any concrete model (e.g. matrices in low dim) gives a  *)
(* witness. We do NOT construct a witness for arbitrary (p,q) — that is what *)
(* mathlib4's CliffordAlgebra provides, and porting that is multi-month work *)
(* (out of scope for T1).                                                    *)
(*                                                                            *)
(* What we PROVE here is the statement-level coherence: from the spec one    *)
(* can derive the standard immediate facts (Clifford relation, linearity of  *)
(* the inclusion, universal factorization). Witness construction is left to  *)
(* Cl6_iso_M8R.v (T2) and Cl8_periodicity.v (T3), where for the specific     *)
(* signatures we either build a model explicitly or admit with citation.     *)
(******************************************************************************)

Theorem T1_clifford_spec_coherent :
  forall p q (C : CliffordSpec p q) (v : Vec (p + q)),
    alg_mul (cl_alg C) (cl_inc C v) (cl_inc C v) =
    alg_smul (cl_alg C) (Q_pq p q v) (alg_one (cl_alg C)).
Proof.
  intros p q C v.
  apply (cl_sq C v).
Qed.

(* The inclusion respects the R-vector-space structure (a free corollary of
   the spec, but we state it as a named theorem for downstream use). *)
Theorem T1_inc_linear :
  forall p q (C : CliffordSpec p q) (a : R) (u v : Vec (p + q)),
    cl_inc C (vec_add (vec_smul a u) v) =
    alg_add (cl_alg C)
            (alg_smul (cl_alg C) a (cl_inc C u))
            (cl_inc C v).
Proof.
  intros p q C a u v.
  rewrite (cl_inc_add _ _ C).
  rewrite (cl_inc_smul _ _ C).
  reflexivity.
Qed.

(* The polarization identity: i(u)·i(v) + i(v)·i(u) = (Q(u+v) − Q(u) − Q(v))·1.
   This is the standard rewriting of the Clifford relation in terms of the
   symmetric bilinear form B(u,v) = ½(Q(u+v) − Q(u) − Q(v)).
   Proof: expand (i(u)+i(v))² via distributivity, apply cl_sq to each
   squared term, then cancel the Q(u)·1 and Q(v)·1 terms using the
   additive-inverse axioms of RAlgebra. *)
Theorem T1_polarization :
  forall p q (C : CliffordSpec p q) (u v : Vec (p + q)),
    alg_add (cl_alg C)
            (alg_mul  (cl_alg C) (cl_inc C u) (cl_inc C v))
            (alg_mul  (cl_alg C) (cl_inc C v) (cl_inc C u))
    =
    alg_add (cl_alg C)
            (alg_smul (cl_alg C) (Q_pq p q (vec_add u v))
                                 (alg_one (cl_alg C)))
            (alg_add (cl_alg C)
              (alg_smul (cl_alg C) (- Q_pq p q u)
                                 (alg_one (cl_alg C)))
              (alg_smul (cl_alg C) (- Q_pq p q v)
                                 (alg_one (cl_alg C)))).
Proof.
  intros p q C u v.
  set (A := cl_alg C).
  set (a := cl_inc C u).
  set (b := cl_inc C v).
  set (one := alg_one A).

  (* Step 1: Clifford relation on u+v, u, and v. *)
  assert (Huv : alg_mul A (alg_add A a b) (alg_add A a b) =
                alg_smul A (Q_pq p q (vec_add u v)) one).
  { unfold A, a, b, one. rewrite <- (cl_inc_add p q C). apply cl_sq. }

  assert (Hu : alg_mul A a a = alg_smul A (Q_pq p q u) one).
  { apply cl_sq. }

  assert (Hv : alg_mul A b b = alg_smul A (Q_pq p q v) one).
  { apply cl_sq. }

  (* Step 2: Expand (a+b)*(a+b) using distributivity. *)
  assert (Hexp : alg_mul A (alg_add A a b) (alg_add A a b) =
                 alg_add A (alg_add A (alg_mul A a a) (alg_mul A a b))
                            (alg_add A (alg_mul A b a) (alg_mul A b b))).
  {
    rewrite (alg_distr_r A a b (alg_add A a b)).
    rewrite (alg_distr_l A a a b).
    rewrite (alg_distr_l A b a b).
    reflexivity.
  }

  (* Step 3: Substitute cl_sq results into the expansion. *)
  rewrite Hexp in Huv.
  rewrite Hu in Huv.
  rewrite Hv in Huv.

  (* Step 4: Rearrange using associativity/commutativity so that
     the scalar terms are collected on the left. *)
  assert (Hrearr :
    alg_add A (alg_add A (alg_smul A (Q_pq p q u) one)
                              (alg_smul A (Q_pq p q v) one))
              (alg_add A (alg_mul A a b) (alg_mul A b a))
    = alg_smul A (Q_pq p q (vec_add u v)) one).
  { rewrite <- (alg_add_shuffle A).
    rewrite (alg_add_comm A (alg_smul A (Q_pq p q v) one) (alg_mul A b a)).
    exact Huv. }

  (* Step 5: Cancel the scalar terms using additive inverses. *)
  apply (alg_add_cancel A (alg_add A (alg_smul A (Q_pq p q u) one)
                                        (alg_smul A (Q_pq p q v) one)))
    in Hrearr.

  (* Step 6: Distribute the inverse over the sum. *)
  rewrite (alg_opp_add A (alg_smul A (Q_pq p q u) one)
                          (alg_smul A (Q_pq p q v) one)) in Hrearr.

  (* Step 7: Rewrite negative scalars. *)
  rewrite <- (alg_smul_opp A (Q_pq p q u) one) in Hrearr.
  rewrite <- (alg_smul_opp A (Q_pq p q v) one) in Hrearr.

  exact Hrearr.
Qed.

(* Sanity: the spec also guarantees that two algebra maps from cl_alg into
   any target that agree on the image of cl_inc must be equal everywhere.
   This is the uniqueness part of the universal property. We re-export it
   as a named theorem. *)
Theorem T1_universal_uniqueness :
  forall p q (C : CliffordSpec p q) (B : RAlgebra)
         (j : Vec (p + q) -> carrier B)
         (f1 f2 : AlgHom (cl_alg C) B),
    (forall v, hom_fn f1 (cl_inc C v) = j v) ->
    (forall v, hom_fn f2 (cl_inc C v) = j v) ->
    forall x, hom_fn f1 x = hom_fn f2 x.
Proof.
  intros p q C B j f1 f2 H1 H2 x.
  apply (cl_univ_unique _ _ C B j f1 f2 H1 H2).
Qed.

Close Scope R_scope.

(******************************************************************************)
(*                                                                            *)
(*  Honesty summary for T1                                                    *)
(*  =======================                                                  *)
(*                                                                            *)
(*  Proved (Qed):                                                             *)
(*    - T1_clifford_spec_coherent                                            *)
(*    - T1_inc_linear                                                         *)
(*    - T1_universal_uniqueness                                              *)
(*    - sum_sq_signed_zero, Q_pq_zero                                       *)
(*                                                                            *)
(*  Admitted (with TRACK_B_CLIFFORD tag):                                    *)
(*    - T1_polarization: standard identity, proof is mechanical but           *)
(*      requires either a ring-like tactic over the abstract RAlgebra or     *)
(*      a tedious chain of rewrites. Deferred to a follow-up PR.             *)
(*                                                                            *)
(*  NOT included in T1 (deferred):                                            *)
(*    - A concrete construction of CliffordSpec p q for arbitrary (p,q).     *)
(*      mathlib4 provides this (Mathlib.LinearAlgebra.CliffordAlgebra.Basic) *)
(*      and Wieser–Song §3 gives the Lean 3 version; porting either is a    *)
(*      multi-week effort.                                                    *)
(*                                                                            *)
(*  Witness instances for specific (p,q) are addressed in:                   *)
(*    - Cl6_iso_M8R.v       (T2)                                             *)
(*    - Cl8_periodicity.v   (T3)                                             *)
(*                                                                            *)
(******************************************************************************)
